# Generated by Django 5.0.6 on 2024-07-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_link_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Precio $'),
        ),
    ]
